title: Mohammed Ehab
url: "https://mohammedehab2002.github.io/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "/resume.pdf"
 - name: "Projects"
   link: "projects"
